In [64]:
import pandas as pd
import sqlite3

df = pd.read_csv('data/loan.csv')
conn = sqlite3.connect('loans.db')
df.to_sql('loans', conn, if_exists='replace', index=False)

/var/folders/_8/zh8sf2z52c738rdw5xv8jvsh0000gp/T/ipykernel_67873/3750938750.py:4: DtypeWarning: Columns (0: desc, 1: next_pymnt_d, 2: verification_status_joint, 3: sec_app_earliest_cr_line, 4: hardship_type, 5: hardship_reason, 6: hardship_status, 7: hardship_start_date, 8: hardship_end_date, 9: payment_plan_start_date, 10: hardship_loan_status, 11: debt_settlement_flag_date, 12: settlement_status, 13: settlement_date) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/loan.csv')

2260668

In [65]:
query = """
SELECT loan_status, COUNT(*) as count
FROM loans
GROUP BY loan_status
ORDER BY count DESC
"""
print('Loan Status Summary')
pd.read_sql(query, conn)

Loan Status Summary

                                         loan_status    count
0                                         Fully Paid  1041952
1                                            Current   919695
2                                        Charged Off   261655
3                                 Late (31-120 days)    21897
4                                    In Grace Period     8952
5                                  Late (16-30 days)     3737
6  Does not meet the credit policy. Status:Fully ...     1988
7  Does not meet the credit policy. Status:Charge...      761
8                                            Default       31

In [79]:
# missing = df.isnull().sum().sort_values(ascending=False)
# missing_pct = (missing / len(df) * 100).round(2)
# pd.DataFrame({'missing count': missing, 'missing_pct': missing_pct}).head(20)

# df = df.drop(columns=['id', 'url', 'member_id'])

missing = df.isnull().sum().sort_values(ascending=False)
missing_pct = (missing / len(df) * 100).round(2)
pd.DataFrame({'missing count': missing, 'missing_pct': missing_pct}).head(20)

                                            missing count  missing_pct
orig_projected_additional_accrued_interest        2252242        99.63
hardship_amount                                   2250055        99.53
hardship_length                                   2250055        99.53
hardship_type                                     2250055        99.53
hardship_reason                                   2250055        99.53
hardship_status                                   2250055        99.53
deferral_term                                     2250055        99.53
hardship_start_date                               2250055        99.53
hardship_last_payment_amount                      2250055        99.53
hardship_end_date                                 2250055        99.53
payment_plan_start_date                           2250055        99.53
hardship_payoff_balance_amount                    2250055        99.53
hardship_loan_status                              2250055        99.53
hardship_dpd                                      2250055        99.53
settlement_term                                   2227612        98.54
debt_settlement_flag_date                         2227612        98.54
settlement_status                                 2227612        98.54
settlement_date                                   2227612        98.54
settlement_amount                                 2227612        98.54
settlement_percentage                             2227612        98.54

In [67]:
query = """
SELECT grade, COUNT(*) as total_loans, SUM(CASE 
    WHEN loan_status LIKE '%Charged off%' OR loan_status LIKE '%Default%' THEN 1 
    ELSE 0 END) as defaults,
    ROUND(100.0 * SUM(CASE
    WHEN loan_status LIKE '%Charged off%' OR loan_status LIKE '%Default%' THEN 1
    ELSE 0 END) / COUNT(*), 2) as default_rate_pct
FROM loans
GROUP BY grade
ORDER BY grade
"""
print('Default Rates by Loan Grade')
pd.read_sql(query, conn)

Default Rates by Loan Grade

  grade  total_loans  defaults  default_rate_pct
0     A       433027     13776              3.18
1     B       663557     51168              7.71
2     C       650053     83419             12.83
3     D       324424     59646             18.39
4     E       135639     35526             26.19
5     F        41800     14358             34.35
6     G        12168      4554             37.43

In [84]:
threshold = 0.5
cols_to_drop = missing_pct[missing_pct > threshold * 100].index.tolist()
print(f"Dropping {len(cols_to_drop)} columns:")
print(cols_to_drop)

df = df.drop(columns=cols_to_drop)
print(f"\nRemaining shape: {df.shape}")

Dropping 41 columns:
['orig_projected_additional_accrued_interest', 'hardship_amount', 'hardship_length', 'hardship_type', 'hardship_reason', 'hardship_status', 'deferral_term', 'hardship_start_date', 'hardship_last_payment_amount', 'hardship_end_date', 'payment_plan_start_date', 'hardship_payoff_balance_amount', 'hardship_loan_status', 'hardship_dpd', 'settlement_term', 'debt_settlement_flag_date', 'settlement_status', 'settlement_date', 'settlement_amount', 'settlement_percentage', 'sec_app_mths_since_last_major_derog', 'sec_app_revol_util', 'revol_bal_joint', 'sec_app_inq_last_6mths', 'sec_app_open_act_il', 'sec_app_num_rev_accts', 'sec_app_chargeoff_within_12_mths', 'sec_app_collections_12_mths_ex_med', 'sec_app_earliest_cr_line', 'sec_app_mort_acc', 'sec_app_open_acc', 'verification_status_joint', 'dti_joint', 'annual_inc_joint', 'desc', 'mths_since_last_record', 'mths_since_recent_bc_dlq', 'mths_since_last_major_derog', 'mths_since_recent_revol_delinq', 'next_pymnt_d', 'mths_since_last_delinq']

Remaining shape: (2260668, 101)

In [37]:
query = """
SELECT *
FROM loans
LIMIT 1
"""
pd.read_sql(query, conn)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,None,None,2500,2500,2500.0,36 months,13.56,84.92,C,C1,...,None,None,Cash,N,None,None,None,None,None,None

In [39]:
pd.set_option('display.max_rows', None)
columns = pd.read_sql("PRAGMA table_info(loans)", conn)
columns

,cid,name,type,notnull,dflt_value,pk
0,0,id,REAL,0,None,0
1,1,member_id,REAL,0,None,0
2,2,loan_amnt,INTEGER,0,None,0
3,3,funded_amnt,INTEGER,0,None,0
4,4,funded_amnt_inv,REAL,0,None,0
5,5,term,TEXT,0,None,0
6,6,int_rate,REAL,0,None,0
7,7,installment,REAL,0,None,0
8,8,grade,TEXT,0,None,0
9,9,sub_grade,TEXT,0,None,0
10,10,emp_title,TEXT,0,None,0
11,11,emp_length,TEXT,0,None,0
12,12,home_ownership,TEXT,0,None,0
13,13,annual_inc,REAL,0,None,0
14,14,verification_status,TEXT,0,None,0
15,15,issue_d,TEXT,0,None,0
16,16,loan_status,TEXT,0,None,0
17,17,pymnt_plan,TEXT,0,None,0
18,18,url,REAL,0,None,0
19,19,desc,TEXT,0,None,0
20,20,purpose,TEXT,0,None,0
21,21,title,TEXT,0,None,0
22,22,zip_code,TEXT,0,None,0
23,23,addr_state,TEXT,0,None,0
24,24,dti,REAL,0,None,0
25,25,delinq_2yrs,REAL,0,None,0
26,26,earliest_cr_line,TEXT,0,None,0
27,27,inq_last_6mths,REAL,0,None,0
28,28,mths_since_last_delinq,REAL,0,None,0
29,29,mths_since_last_record,REAL,0,None,0
30,30,open_acc,REAL,0,None,0
31,31,pub_rec,REAL,0,None,0
32,32,revol_bal,INTEGER,0,None,0
33,33,revol_util,REAL,0,None,0
34,34,total_acc,REAL,0,None,0
35,35,initial_list_status,TEXT,0,None,0
36,36,out_prncp,REAL,0,None,0
37,37,out_prncp_inv,REAL,0,None,0
38,38,total_pymnt,REAL,0,None,0
39,39,total_pymnt_inv,REAL,0,None,0
40,40,total_rec_prncp,REAL,0,None,0
41,41,total_rec_int,REAL,0,None,0
42,42,total_rec_late_fee,REAL,0,None,0
43,43,recoveries,REAL,0,None,0
44,44,collection_recovery_fee,REAL,0,None,0
45,45,last_pymnt_d,TEXT,0,None,0
46,46,last_pymnt_amnt,REAL,0,None,0
47,47,next_pymnt_d,TEXT,0,None,0
48,48,last_credit_pull_d,TEXT,0,None,0
49,49,collections_12_mths_ex_med,REAL,0,None,0
50,50,mths_since_last_major_derog,REAL,0,None,0
51,51,policy_code,INTEGER,0,None,0
52,52,application_type,TEXT,0,None,0
53,53,annual_inc_joint,REAL,0,None,0
54,54,dti_joint,REAL,0,None,0
55,55,verification_status_joint,TEXT,0,None,0
56,56,acc_now_delinq,REAL,0,None,0
57,57,tot_coll_amt,REAL,0,None,0
58,58,tot_cur_bal,REAL,0,None,0
59,59,open_acc_6m,REAL,0,None,0
60,60,open_act_il,REAL,0,None,0
61,61,open_il_12m,REAL,0,None,0
62,62,open_il_24m,REAL,0,None,0
63,63,mths_since_rcnt_il,REAL,0,None,0
64,64,total_bal_il,REAL,0,None,0
65,65,il_util,REAL,0,None,0
66,66,open_rv_12m,REAL,0,None,0
67,67,open_rv_24m,REAL,0,None,0
68,68,max_bal_bc,REAL,0,None,0
69,69,all_util,REAL,0,None,0
70,70,total_rev_hi_lim,REAL,0,None,0
71,71,inq_fi,REAL,0,None,0
72,72,total_cu_tl,REAL,0,None,0
73,73,inq_last_12m,REAL,0,None,0
74,74,acc_open_past_24mths,REAL,0,None,0
75,75,avg_cur_bal,REAL,0,None,0
76,76,bc_open_to_buy,REAL,0,None,0
77,77,bc_util,REAL,0,None,0
78,78,chargeoff_within_12_mths,REAL,0,None,0
79,79,delinq_amnt,REAL,0,None,0
80,80,mo_sin_old_il_acct,REAL,0,None,0
81,81,mo_sin_old_rev_tl_op,REAL,0,None,0
82,82,mo_sin_rcnt_rev_tl_op,REAL,0,None,0
83,83,mo_sin_rcnt_tl,REAL,0,None,0
84,84,mort_acc,REAL,0,None,0
85,85,mths_since_recent_bc,REAL,0,None,0
86,86,mths_since_recent_bc_dlq,REAL,0,None,0
87,87,mths_since_recent_inq,REAL,0,None,0
88,88,mths_since_recent_revol_delinq,REAL,0,None,0
89,89,num_accts_ever_120_pd,REAL,0,None,0
90,90,num_actv_bc_tl,REAL,0,None,0
91,91,num_actv_rev_tl,REAL,0,None,0
92,92,num_bc_sats,REAL,0,None,0
93,93,num_bc_tl,REAL,0,None,0
94,94,num_il_tl,REAL,0,None,0
95,95,num_op_rev_tl,REAL,0,None,0
96,96,num_rev_accts,REAL,0,None,0
97,97,num_rev_tl_bal_gt_0,REAL,0,None,0
98,98,num_sats,REAL,0,None,0
99,99,num_tl_120dpd_2m,REAL,0,None,0
100,100,num_tl_30dpd,REAL,0,None,0
101,101,num_tl_90g_dpd_24m,REAL,0,None,0
102,102,num_tl_op_past_12m,REAL,0,None,0
103,103,pct_tl_nvr_dlq,REAL,0,None,0
104,104,percent_bc_gt_75,REAL,0,None,0
105,105,pub_rec_bankruptcies,REAL,0,None,0
106,106,tax_liens,REAL,0,None,0
107,107,tot_hi_cred_lim,REAL,0,None,0
108,108,total_bal_ex_mort,REAL,0,None,0
109,109,total_bc_limit,REAL,0,None,0
110,110,total_il_high_credit_limit,REAL,0,None,0
111,111,revol_bal_joint,REAL,0,None,0
112,112,sec_app_earliest_cr_line,TEXT,0,None,0
113,113,sec_app_inq_last_6mths,REAL,0,None,0
114,114,sec_app_mort_acc,REAL,0,None,0
115,115,sec_app_open_acc,REAL,0,None,0
116,116,sec_app_revol_util,REAL,0,None,0
117,117,sec_app_open_act_il,REAL,0,None,0
118,118,sec_app_num_rev_accts,REAL,0,None,0
119,119,sec_app_chargeoff_within_12_mths,REAL,0,None,0
120,120,sec_app_collections_12_mths_ex_med,REAL,0,None,0
121,121,sec_app_mths_since_last_major_derog,REAL,0,None,0
122,122,hardship_flag,TEXT,0,None,0
123,123,hardship_type,TEXT,0,None,0
124,124,hardship_reason,TEXT,0,None,0
125,125,hardship_status,TEXT,0,None,0
126,126,deferral_term,REAL,0,None,0
127,127,hardship_amount,REAL,0,None,0
128,128,hardship_start_date,TEXT,0,None,0
129,129,hardship_end_date,TEXT,0,None,0
130,130,payment_plan_start_date,TEXT,0,None,0
131,131,hardship_length,REAL,0,None,0
132,132,hardship_dpd,REAL,0,None,0
133,133,hardship_loan_status,TEXT,0,None,0
134,134,orig_projected_additional_accrued_interest,REAL,0,None,0
135,135,hardship_payoff_balance_amount,REAL,0,None,0
136,136,hardship_last_payment_amount,REAL,0,None,0
137,137,disbursement_method,TEXT,0,None,0
138,138,debt_settlement_flag,TEXT,0,None,0
139,139,debt_settlement_flag_date,TEXT,0,None,0
140,140,settlement_status,TEXT,0,None,0
141,141,settlement_date,TEXT,0,None,0
142,142,settlement_amount,REAL,0,None,0
143,143,settlement_percentage,REAL,0,None,0
144,144,settlement_term,REAL,0,None,0